import Foundation

/// A complete widget pipeline specification generated by the LLM.
/// Describes a DAG of skill invocations that the app executes deterministically.
struct WidgetPipelineSpec: Codable {
    /// Human-readable title for the widget
    let title: String

    /// How often to refresh the widget data, in seconds (minimum 300)
    let refreshIntervalSeconds: Int

    /// Ordered list of pipeline steps to execute
    let pipeline: [PipelineStep]

    /// Unique identifier for this widget instance
    var widgetId: UUID

    /// Optional LLM thinking/reasoning that produced this spec
    var thinking: String?

    enum CodingKeys: String, CodingKey {
        case title
        case refreshIntervalSeconds = "refresh_interval_seconds"
        case pipeline
        case widgetId = "widget_id"
        case thinking
    }

    init(
        title: String,
        refreshIntervalSeconds: Int = 300,
        pipeline: [PipelineStep],
        widgetId: UUID = UUID(),
        thinking: String? = nil
    ) {
        self.title = title
        self.refreshIntervalSeconds = refreshIntervalSeconds
        self.pipeline = pipeline
        self.widgetId = widgetId
        self.thinking = thinking
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        title = try container.decode(String.self, forKey: .title)
        refreshIntervalSeconds = try container.decode(Int.self, forKey: .refreshIntervalSeconds)
        pipeline = try container.decode([PipelineStep].self, forKey: .pipeline)
        widgetId = try container.decodeIfPresent(UUID.self, forKey: .widgetId) ?? UUID()
        thinking = try container.decodeIfPresent(String.self, forKey: .thinking)
    }
}

/// A single step in the execution pipeline.
struct PipelineStep: Codable {
    /// Unique identifier for this step, referenced by later steps via `{{step_id.output}}`
    let id: String

    /// The skill to invoke
    let skill: SkillName

    /// Skill-specific parameters. May contain `{{other_step.output}}` references.
    let params: [String: AnyCodable]

    init(id: String, skill: SkillName, params: [String: AnyCodable] = [:]) {
        self.id = id
        self.skill = skill
        self.params = params
    }
}

/// A validated pipeline spec that has passed all validation checks.
/// Can only be created by `SpecValidator`.
struct ValidatedSpec {
    let spec: WidgetPipelineSpec

    /// Internal initializer — only `SpecValidator` should create these.
    init(trusted spec: WidgetPipelineSpec) {
        self.spec = spec
    }
}
