import Foundation

/// A unified module definition — the single primitive for widgets, extensions, skills, and blockers.
/// Generated by the LLM from natural language and stored as JSON.
struct ModuleManifest: Codable, Identifiable {
    /// Stable identity for edits
    var id: UUID

    /// Display name
    var name: String

    /// Human-readable description (also used by LLM for tool selection)
    var description: String

    /// Auto-incremented on each edit
    var version: Int

    /// Capability grants — determines which `wheel.*` APIs are injected
    var permissions: [ModulePermission]

    /// When this module activates
    var triggers: [ModuleTrigger]

    /// WKContentRuleList JSON for network-level blocking (ad blockers, trackers)
    var contentRules: [[String: Any]]?

    /// CSS strings injected into matching pages
    var styles: [String]?

    /// JavaScript executed in the page context (WKUserScript in isolated WKContentWorld)
    var contentScript: String?

    /// JavaScript executed in a sandboxed JSContext (no DOM access)
    var backgroundScript: String?

    /// Whether the module is currently active
    var isEnabled: Bool

    /// Creation timestamp
    var createdAt: Date

    /// Last modified timestamp
    var updatedAt: Date

    init(
        id: UUID = UUID(),
        name: String,
        description: String,
        version: Int = 1,
        permissions: [ModulePermission] = [],
        triggers: [ModuleTrigger] = [],
        contentRules: [[String: Any]]? = nil,
        styles: [String]? = nil,
        contentScript: String? = nil,
        backgroundScript: String? = nil,
        isEnabled: Bool = true,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.version = version
        self.permissions = permissions
        self.triggers = triggers
        self.contentRules = contentRules
        self.styles = styles
        self.contentScript = contentScript
        self.backgroundScript = backgroundScript
        self.isEnabled = isEnabled
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    // MARK: - Codable

    enum CodingKeys: String, CodingKey {
        case id, name, description, version, permissions, triggers
        case contentRules = "content_rules"
        case styles
        case contentScript = "content_script"
        case backgroundScript = "background_script"
        case isEnabled = "is_enabled"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        name = try container.decode(String.self, forKey: .name)
        description = try container.decode(String.self, forKey: .description)
        version = try container.decodeIfPresent(Int.self, forKey: .version) ?? 1
        permissions = try container.decode([ModulePermission].self, forKey: .permissions)
        triggers = try container.decode([ModuleTrigger].self, forKey: .triggers)

        // contentRules is [[String: Any]] — decode via AnyCodable
        if let rulesArray = try container.decodeIfPresent([AnyCodable].self, forKey: .contentRules) {
            contentRules = rulesArray.compactMap { $0.dictionaryValue }
        } else {
            contentRules = nil
        }

        styles = try container.decodeIfPresent([String].self, forKey: .styles)
        contentScript = try container.decodeIfPresent(String.self, forKey: .contentScript)
        backgroundScript = try container.decodeIfPresent(String.self, forKey: .backgroundScript)
        isEnabled = try container.decodeIfPresent(Bool.self, forKey: .isEnabled) ?? true
        createdAt = try container.decodeIfPresent(Date.self, forKey: .createdAt) ?? Date()
        updatedAt = try container.decodeIfPresent(Date.self, forKey: .updatedAt) ?? Date()
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(version, forKey: .version)
        try container.encode(permissions, forKey: .permissions)
        try container.encode(triggers, forKey: .triggers)

        if let rules = contentRules {
            let codableRules = rules.map { AnyCodable($0) }
            try container.encode(codableRules, forKey: .contentRules)
        }

        try container.encodeIfPresent(styles, forKey: .styles)
        try container.encodeIfPresent(contentScript, forKey: .contentScript)
        try container.encodeIfPresent(backgroundScript, forKey: .backgroundScript)
        try container.encode(isEnabled, forKey: .isEnabled)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }

    // MARK: - Derived Properties

    /// The type of module inferred from its trigger + code configuration.
    var moduleType: ModuleType {
        if contentRules != nil && contentScript == nil && backgroundScript == nil {
            return .blocker
        }
        if triggers.contains(where: { $0.type == .manual }) && backgroundScript != nil {
            return .widget
        }
        if triggers.contains(where: { $0.type == .schedule }) {
            return .widget
        }
        if triggers.contains(where: { $0.type == .manual }) {
            return .skill
        }
        if triggers.contains(where: { $0.type == .pageLoad }) {
            return .extension_
        }
        return .extension_
    }

    /// Whether this module has any executable JavaScript code.
    var hasCode: Bool {
        contentScript != nil || backgroundScript != nil
    }

    /// URL patterns this module matches against (from pageLoad triggers).
    var urlPatterns: [String] {
        triggers.compactMap { trigger in
            if trigger.type == .pageLoad { return trigger.urlPattern }
            return nil
        }
    }
}

// MARK: - Module Type

enum ModuleType: String, Codable {
    case widget       // schedule/manual trigger + backgroundScript + wheel.render()
    case extension_   // pageLoad trigger + contentScript/styles
    case skill        // manual trigger, used as LLM tool
    case blocker      // always trigger + contentRules only
}

// MARK: - Trigger

struct ModuleTrigger: Codable, Equatable {
    let type: TriggerType
    var urlPattern: String?
    var intervalSeconds: Int?

    enum TriggerType: String, Codable {
        case pageLoad = "page_load"
        case manual
        case schedule
        case always
    }
}

// MARK: - Permission

enum ModulePermission: String, Codable, CaseIterable {
    case domQuery = "dom.query"
    case domModify = "dom.modify"
    case domCSSInject = "dom.css_inject"
    case domObserve = "dom.observe"
    case storageLocal = "storage.local"
    case networkFetch = "network.fetch"
    case schedule = "schedule"
    case notifications = "notifications"
    case contentRules = "content_rules"
    case pageRead = "page.read"

    var displayName: String {
        switch self {
        case .domQuery: return "Read DOM elements"
        case .domModify: return "Modify/remove DOM elements"
        case .domCSSInject: return "Inject/remove CSS"
        case .domObserve: return "Observe DOM changes"
        case .storageLocal: return "Local storage (512KB)"
        case .networkFetch: return "HTTP requests"
        case .schedule: return "Background scheduling"
        case .notifications: return "macOS notifications"
        case .contentRules: return "Network request blocking"
        case .pageRead: return "Read page URL/title"
        }
    }
}
